#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

echo "This script helps generate commands to wire Prowlarr, Radarr, Lidarr, Sonarr, and Overseerr to your download clients and media servers."

read -p "Git repository URL to pull configuration from [https://github.com/duckeydev/IAMARR]: " GIT_REPO
GIT_REPO=${GIT_REPO:-https://github.com/duckeydev/IAMARR}
if [ -n "$GIT_REPO" ]; then
  read -p "Target directory to clone into [./arr-deploy]: " TARGET_DIR
  TARGET_DIR=${TARGET_DIR:-./arr-deploy}
  if [ -d "$TARGET_DIR/.git" ]; then
    echo "Updating existing clone in $TARGET_DIR"
    git -C "$TARGET_DIR" pull || true
  else
    echo "Cloning $GIT_REPO -> $TARGET_DIR"
    git clone "$GIT_REPO" "$TARGET_DIR"
  fi
  WORK_DIR="$TARGET_DIR"
else
  WORK_DIR="$ROOT_DIR"
fi

read -p "Absolute media root path [/mnt/media]: " MEDIA_ROOT
MEDIA_ROOT=${MEDIA_ROOT:-/mnt/media}
read -p "Absolute torrents root path [/mnt/torrents]: " TORRENTS_ROOT
TORRENTS_ROOT=${TORRENTS_ROOT:-/mnt/torrents}
read -p "Absolute config root path [/var/lib/arr-config]: " CONFIG_ROOT
CONFIG_ROOT=${CONFIG_ROOT:-/var/lib/arr-config}

echo "Creating directories under provided roots (if missing)"
mkdir -p "${MEDIA_ROOT}/music" "${MEDIA_ROOT}/movies" "${MEDIA_ROOT}/tv"
mkdir -p "${TORRENTS_ROOT}/music" "${TORRENTS_ROOT}/movies" "${TORRENTS_ROOT}/tv"
mkdir -p "${CONFIG_ROOT}"

echo "Updating compose files in $WORK_DIR to use absolute paths you provided."
# Replace ./data/media -> MEDIA_ROOT and ./data/torrents -> TORRENTS_ROOT and ./config -> CONFIG_ROOT
find "$WORK_DIR" -type f -name "docker-compose*.yml" -o -name "*.yml" | while read -r f; do
  sed -i "s|./data/media|${MEDIA_ROOT}|g" "$f" || true
  sed -i "s|./data/torrents|${TORRENTS_ROOT}|g" "$f" || true
  sed -i "s|./data/media|${MEDIA_ROOT}|g" "$f" || true
  sed -i "s|./config/|${CONFIG_ROOT}/|g" "$f" || true
done

echo "Compose files updated (dry run - files modified in place)."

read -p "Prowlarr URL [http://localhost:9696]: " PROWLARR_URL
PROWLARR_URL=${PROWLARR_URL:-http://localhost:9696}
read -p "Prowlarr API key: " PROWLARR_API

read -p "Radarr URL [http://localhost:7878]: " RADARR_URL
RADARR_URL=${RADARR_URL:-http://localhost:7878}
read -p "Radarr API key: " RADARR_API

read -p "Lidarr URL [http://localhost:8686]: " LIDARR_URL
LIDARR_URL=${LIDARR_URL:-http://localhost:8686}
read -p "Lidarr API key: " LIDARR_API

read -p "Sonarr URL [http://localhost:8989]: " SONARR_URL
SONARR_URL=${SONARR_URL:-http://localhost:8989}
read -p "Sonarr API key: " SONARR_API

read -p "qBittorrent URL [http://localhost:${QBITTORRENT_WEBUI_PORT:-8080}]: " QBIT_URL
QBIT_URL=${QBIT_URL:-http://localhost:${QBITTORRENT_WEBUI_PORT:-8080}}
read -p "qBittorrent username: " QBIT_USER
read -s -p "qBittorrent password: " QBIT_PASS
echo

read -p "Transmission URL [http://localhost:${TRANSMISSION_WEBUI_PORT:-9091}]: " TRANS_URL
TRANS_URL=${TRANS_URL:-http://localhost:${TRANSMISSION_WEBUI_PORT:-9091}}
read -p "Transmission username (leave blank if none): " TRANS_USER
if [ -n "$TRANS_USER" ]; then
  read -s -p "Transmission password: " TRANS_PASS
  echo
fi

read -p "Overseerr URL [http://localhost:5055]: " OVERSEERR_URL
OVERSEERR_URL=${OVERSEERR_URL:-http://localhost:5055}
read -p "Overseerr API key (leave blank to skip): " OVERSEERR_API

read -p "Jellyfin URL [http://localhost:8096]: " JELLYFIN_URL
JELLYFIN_URL=${JELLYFIN_URL:-http://localhost:8096}
read -p "Jellyfin admin username: " JELLYFIN_USER
read -s -p "Jellyfin admin password: " JELLYFIN_PASS
echo

# Validate simple connectivity
echo "\nValidating connections (simple)..."
set +e
curl -sS -H "X-Api-Key: ${PROWLARR_API}" "${PROWLARR_URL}/api/v1/system/status" >/dev/null 2>&1
if [ $? -eq 0 ]; then echo "Prowlarr reachable"; else echo "Warning: Prowlarr not reachable or API key invalid"; fi
curl -sS -H "X-Api-Key: ${RADARR_API}" "${RADARR_URL}/api/v3/system/status" >/dev/null 2>&1
if [ $? -eq 0 ]; then echo "Radarr reachable"; else echo "Warning: Radarr not reachable or API key invalid"; fi
curl -sS -H "X-Api-Key: ${LIDARR_API}" "${LIDARR_URL}/api/v1/system/status" >/dev/null 2>&1
if [ $? -eq 0 ]; then echo "Lidarr reachable"; else echo "Warning: Lidarr not reachable or API key invalid"; fi
curl -sS -H "X-Api-Key: ${SONARR_API}" "${SONARR_URL}/api/v3/system/status" >/dev/null 2>&1
if [ $? -eq 0 ]; then echo "Sonarr reachable"; else echo "Warning: Sonarr not reachable or API key invalid"; fi
set -e

OUT_SCRIPT="${ROOT_DIR}/wiring-commands.sh"
cat > "$OUT_SCRIPT" <<EOF
#!/usr/bin/env bash
# Wiring commands generated by auto_wire.sh on $(date)
# Review before running. This script will perform API calls to configure your services.

set -euo pipefail

PROWLARR_URL="${PROWLARR_URL}"
PROWLARR_API="${PROWLARR_API}"
RADARR_URL="${RADARR_URL}"
RADARR_API="${RADARR_API}"
LIDARR_URL="${LIDARR_URL}"
LIDARR_API="${LIDARR_API}"
SONARR_URL="${SONARR_URL}"
SONARR_API="${SONARR_API}"
QBIT_URL="${QBIT_URL}"
QBIT_USER="${QBIT_USER}"
QBIT_PASS="${QBIT_PASS}"
TRANS_URL="${TRANS_URL}"
TRANS_USER="${TRANS_USER}"
TRANS_PASS="${TRANS_PASS}"
OVERSEERR_URL="${OVERSEERR_URL}"
OVERSEERR_API="${OVERSEERR_API}"
JELLYFIN_URL="${JELLYFIN_URL}"
JELLYFIN_USER="${JELLYFIN_USER}"
JELLYFIN_PASS="${JELLYFIN_PASS}"

cat <<EOD
Dry-run wiring plan below. To execute these commands, review them and run this file.
EOD

# 1) Add Prowlarr as an "App" to Radarr/Lidarr/Sonarr via Prowlarr API (so indexers are synced)
# Note: This uses Prowlarr's Apps endpoint to register the target apps. Prowlarr will then be able to manage indexers for them.
# Example command (adjust if your Prowlarr version differs):

cat <<CMD
curl -s -X POST "${PROWLARR_URL}/api/v1/apps" \
  -H "X-Api-Key: ${PROWLARR_API}" \
  -H 'Content-Type: application/json' \
  -d '{"Name":"Radarr","Type":"Radarr","Enabled":true,"Fields":[{"Key":"url","Value":"${RADARR_URL}"},{"Key":"apikey","Value":"${RADARR_API}"}]}'
CMD

cat <<CMD
curl -s -X POST "${PROWLARR_URL}/api/v1/apps" \
  -H "X-Api-Key: ${PROWLARR_API}" \
  -H 'Content-Type: application/json' \
  -d '{"Name":"Lidarr","Type":"Lidarr","Enabled":true,"Fields":[{"Key":"url","Value":"${LIDARR_URL}"},{"Key":"apikey","Value":"${LIDARR_API}"}]}'
CMD

cat <<CMD
curl -s -X POST "${PROWLARR_URL}/api/v1/apps" \
  -H "X-Api-Key: ${PROWLARR_API}" \
  -H 'Content-Type: application/json' \
  -d '{"Name":"Sonarr","Type":"Sonarr","Enabled":true,"Fields":[{"Key":"url","Value":"${SONARR_URL}"},{"Key":"apikey","Value":"${SONARR_API}"}]}'
CMD

# 2) Add qBittorrent as a download client to Radarr/Lidarr/Sonarr
# These POST payloads follow common Radarr/Sonarr formats; verify the implementations match your versions before running.

cat <<CMD
curl -s -X POST "${RADARR_URL}/api/v3/downloadclient" \
  -H "X-Api-Key: ${RADARR_API}" \
  -H 'Content-Type: application/json' \
  -d '{"enable":true,"name":"qBittorrent","implementation":"qBittorrent","protocol":"torrent","settings":{"host":"${QBIT_URL}","username":"${QBIT_USER}","password":"${QBIT_PASS}"}}'
CMD

cat <<CMD
curl -s -X POST "${LIDARR_URL}/api/v1/downloadclient" \
  -H "X-Api-Key: ${LIDARR_API}" \
  -H 'Content-Type: application/json' \
  -d '{"enable":true,"name":"qBittorrent","implementation":"qBittorrent","settings":{"host":"${QBIT_URL}","username":"${QBIT_USER}","password":"${QBIT_PASS}"}}'
CMD

cat <<CMD
curl -s -X POST "${SONARR_URL}/api/v3/downloadclient" \
  -H "X-Api-Key: ${SONARR_API}" \
  -H 'Content-Type: application/json' \
  -d '{"enable":true,"name":"qBittorrent","implementation":"qBittorrent","settings":{"host":"${QBIT_URL}","username":"${QBIT_USER}","password":"${QBIT_PASS}"}}'
CMD

# 3) Add Transmission as alternative download client (examples)
cat <<CMD
curl -s -X POST "${RADARR_URL}/api/v3/downloadclient" \
  -H "X-Api-Key: ${RADARR_API}" \
  -H 'Content-Type: application/json' \
  -d '{"enable":true,"name":"Transmission","implementation":"Transmission","settings":{"host":"${TRANS_URL}","username":"${TRANS_USER}","password":"${TRANS_PASS}"}}'
CMD

# 4) Configure Overseerr to use Jellyfin (if API available)
if [ -n "${OVERSEERR_API}" ]; then
cat <<CMD
curl -s -X POST "${OVERSEERR_URL}/api/v1/settings/jellyfin" \
  -H "X-Api-Key: ${OVERSEERR_API}" \
  -H 'Content-Type: application/json' \
  -d '{"serverUrl":"${JELLYFIN_URL}","username":"${JELLYFIN_USER}","password":"${JELLYFIN_PASS}"}'
CMD
fi

EOF

chmod +x "$OUT_SCRIPT"

echo "Wiring commands written to $OUT_SCRIPT"

echo "Review $OUT_SCRIPT, then run it to execute the wiring commands (or copy individual curl lines)."
